##  What is a Tensor?

A **tensor** is a **multi-dimensional array** (generalization of scalars, vectors, matrices). ([PyTorch Documentation][1])

Tensors are the fundamental building block of machine learning.
Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape `[3, 224, 224]` which would mean `[colour_channels, height, width]`, as in the image has 3 colour channels `(red, green, blue)`, a height of 224 pixels and a width of 224 pixels.

### Simple mapping:

* 0D → Scalar → `5`
* 1D → Vector → `[1,2,3]`
* 2D → Matrix → `[[1,2],[3,4]]`
* nD → Tensor → used in deep learning

 Key properties:

* **shape** → dimensions
* **dtype** → data type
* **device** → CPU / GPU ([PyTorch Documentation][2])

---


In [1]:
import torch

```python
torch.tensor(data, dtype, device, requires_grad, pin_memory)
```
---

###  `data`

**Info:** Input data used to create the tensor; defines values and initial shape.
**Possible values:**

* Python lists/tuples → `[1,2,3]`, `[[1,2],[3,4]]`
* NumPy arrays → `np.array([...])`
* Scalars → `5`, `3.14`
* Existing tensors

---

###  `dtype`

**Info:** Specifies the **data type (numerical precision/format)** of tensor elements.
**Possible values:**

* `torch.float32` (default for floats)
* `torch.float64`
* `torch.int32`, `torch.int64`
* `torch.bool`
* `torch.uint8`

---

###  `device`

**Info:** Determines where the tensor is stored and computed (hardware allocation).
**Possible values:**

* `'cpu'`
* `'cuda'` (GPU, if available)
* `'cuda:0'`, `'cuda:1'` (specific GPU index)

---

###  `requires_grad`

**Info:** Enables **automatic gradient tracking** for backpropagation (used in training).
**Possible values:**

* `True` → track gradients
* `False` (default) → no tracking

---

###  `pin_memory`

**Info:** Allocates tensor in **pinned (page-locked) memory** for faster CPU → GPU transfer.
**Possible values:**

* `True` → faster transfer (used in DataLoader pipelines)
* `False` (default)

---

####  Key Insight

This function acts as a **tensor constructor with configurable attributes**, allowing control over:

* memory placement
* numerical representation
* gradient behavior

---

####  Summary

* **dtype** → numerical data representation
* **device allocation** → hardware placement of tensor
* **gradient tracking** → storing derivatives for optimization
* **pinned memory** → optimized memory for faster data transfer

---


In [19]:
type(torch.tensor([23,4,3]))

torch.Tensor

##  1. Create Tensor from Data (Most Basic)

```python
import torch

t = torch.tensor([1, 2, 3])
t2 = torch.tensor([[1, 2], [3, 4]])
```

✔ Always copies data (important detail) ([PyTorch Documentation][1])

---

#### Scaler

In [2]:
scaler = torch.tensor(2)
scaler, scaler.ndim, type(scaler), scaler.item(), type(scaler.item())

(tensor(2), 0, torch.Tensor, 2, int)

#### Vector

In [3]:
vector = torch.tensor([1,3,4,5])
vector, vector.ndim, vector.shape, type(vector), vector[1].item()

# vector.item() ---> ERROR becuase only one element can be converted to number not a bunch of numbers

(tensor([1, 3, 4, 5]), 1, torch.Size([4]), torch.Tensor, 3)

#### Matrix

In [4]:
MATRIX = torch.tensor([[1,3],
                       [4,6]])
MATRIX, MATRIX.ndim, MATRIX.shape, type(MATRIX), MATRIX[1][1].item()

(tensor([[1, 3],
         [4, 6]]),
 2,
 torch.Size([2, 2]),
 torch.Tensor,
 6)

##  2. Empty Tensor (Uninitialized)

```python
torch.empty(2, 3)
```

 Memory allocated but values = garbage
✔ Useful for **performance optimization**

---


In [5]:
empty_tensor = torch.empty(2,2,3, dtype=int)
empty_tensor, empty_tensor.shape, empty_tensor.ndim, empty_tensor.type(), type(empty_tensor)

(tensor([[[6187223417120,             0,             0],
          [            0,             0,             0]],
 
         [[            0,             0,             0],
          [            0,             0,             0]]]),
 torch.Size([2, 2, 3]),
 3,
 'torch.LongTensor',
 torch.Tensor)

---

# HOW TO UNDERSTAND TENSOR

#### ***Totally same as NumPy Arrays***

**shape = [x, y, z, a, b, d, ..., w, r, c]**

```
c = number of columns
r = number of rows
w = w times c x r
d = d times  ..., w, r, c
b = b times d, ..., w, r, c
.
.
.
x = x times y, z, a, b, d, ..., w, r, c
```
~~~
Always have [] -> container brackets
then x number of []
then y number of [] inside each x number of []
then z number of [] inside each y number of []
..
...
....
then r number of rows each in [] x c number of columns as a matrix insided each w number of []
~~~

---

### DataType of tensors
The default dtype for tensors is torch.float32 i.e. float except when data given to create tensors are all integers

**```torch.Tensor``` itself is an alias of FloatTensor (float32)**

You can change default using:
```torch.set_default_dtype(torch.float64)```
* Can only set for float dtypes*

#### Why float32 is default?
* Balanced precision vs performance
* Faster on GPUs
* Lower memory than float64

This is an important optimization trade-off in deep learning.


---

#  3. Zeros Tensor

```python
torch.zeros(2, 3)
```

✔ All values = 0 ([PyTorch Wiki][3])

---

In [6]:
zero_tensor = torch.zeros(2,5, dtype=int)
zero_tensor, zero_tensor.dtype, 

(tensor([[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]),
 torch.int64)

#  4. Ones Tensor

```python
torch.ones(2, 3)
```

✔ All values = 1 ([Codecademy][4])

---

In [ ]:
#Ones Tensor
ones_tensor = torch.ones(3,4)
ones_tensor, ones_tensor.dtype


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float64)


#  5. Random Tensor (Uniform Distribution)

```python
torch.rand(2, 3)
```

✔ Values between `[0,1)` ([PyTorch Wiki][5])

---

In [16]:
random_tensor = torch.rand(3,4)
random_tensor, random_tensor.shape, random_tensor.size, random_tensor.dtype, random_tensor.ndim

'''
🔴 Why this error occurs?
torch.rand(3,4, dtype=torch.int32)

👉 Error:

"check_uniform_bounds" not implemented for 'Int'
✔ Reason:
    * torch.rand() generates values from a uniform distribution → continuous values between [0, 1)
    * This operation is defined only for floating-point tensors, not integers (pytorch.org
)

👉 Integer tensors cannot represent continuous random values
'''

'\n🔴 Why this error occurs?\ntorch.rand(3,4, dtype=torch.int32)\n\n👉 Error:\n\n"check_uniform_bounds" not implemented for \'Int\'\n✔ Reason:\n    * torch.rand() generates values from a uniform distribution → continuous values between [0, 1)\n    * This operation is defined only for floating-point tensors, not integers (pytorch.org\n)\n\n👉 Integer tensors cannot represent continuous random values\n'


#  6. Random Normal (Gaussian Distribution)

```python
torch.randn(2, 3)
```

✔ Mean = 0, Std = 1
 Used heavily in neural networks

---

In [ ]:
torch.tensor()

#  7. Integer Random Tensor

```python
torch.randint(0, 10, (2, 3))
```

✔ Values from 0 → 9

---

#  8. Range-Based Tensors

### arange (like range)

```python
torch.arange(0, 10, 2)
```

### linspace (fixed steps)

```python
torch.linspace(0, 1, steps=5)
```

---

#  9. Identity Matrix

```python
torch.eye(3)
```

✔ Diagonal = 1

---

#  10. Like Functions (Very Important)

Creates tensor based on another tensor:

```python
x = torch.rand(2,3)

torch.zeros_like(x)
torch.ones_like(x)
torch.rand_like(x)
```

 Maintains shape + dtype (important abstraction)

---

#  11. Custom Value Tensor

```python
torch.full((2,3), 7)
```

✔ All values = 7

---

#  12. From NumPy

```python
import numpy as np

arr = np.array([1,2,3])
torch.tensor(arr)
```

---

#  13. Tensor with Specific Properties

```python
torch.zeros(2,3, dtype=torch.float32, device='cpu', requires_grad=True)
```

 Key arguments:

* `dtype` → data type
* `device` → cpu / cuda
* `requires_grad` → for backpropagation

---

#  14. New Tensor from Existing Tensor

```python
x = torch.tensor([1,2,3])
x.new_zeros(2,3)
```

✔ Same dtype + device ([PyTorch Wiki][6])

---

#  15. Shape Specification (Important Pattern)

All creation functions follow:

```python
torch.function_name(size)
```

Example:

```python
torch.rand(3,4,5)
```

 This is called a **factory function pattern** ([PyTorch Documentation][7])

---

#  Summary (Very Important)

| Function           | Purpose                 |
| ------------------ | ----------------------- |
| `torch.tensor()`   | From data               |
| `torch.zeros()`    | All zeros               |
| `torch.ones()`     | All ones                |
| `torch.rand()`     | Uniform random          |
| `torch.randn()`    | Normal random           |
| `torch.randint()`  | Integer random          |
| `torch.arange()`   | Sequence                |
| `torch.linspace()` | Even spacing            |
| `torch.eye()`      | Identity                |
| `*_like()`         | Based on another tensor |

---

#  Vocabulary Boost

* **Tensor initialization** → creating tensors
* **Uniform distribution** → equal probability values
* **Gaussian distribution** → bell curve distribution
* **dtype** → numerical precision type
* **Device allocation** → CPU/GPU placement

---

##  Guidance (Important for you)

 First master:

1. `tensor()`
2. `zeros(), ones()`
3. `rand(), randn()`
4. `*_like()`

These are used in **90% of deep learning workflows**.

---