In [67]:
import torch

## 1. Basic Matrix Representation in PyTorch

---

### Tensor Types (Quick Recap)

| Type   | Dimension | Example         |
| ------ | --------- | --------------- |
| Scalar | 0D        | `5`             |
| Vector | 1D        | `[1,2,3]`       |
| Matrix | 2D        | `[[1,2],[3,4]]` |
| Tensor | nD        | `3D, 4D...`     |

---

In [68]:
scaler = torch.tensor(5)
vector = torch.tensor([1,2,3,3,5,5])
matrix = torch.tensor([[1,3,4],
                       [3,44,5]])
tensor = torch.tensor([[[1,2,3],
                        [4,5,6]],
                       
                       [[11,22,33],
                       [44,55,66]]])
print(f'scaler: {scaler}\nvector: {vector}\n\nmatrix:\n{matrix}\n\ntensor:\n{tensor}')
print(f'Shape of matrix: {matrix.shape}\nShape of tensor: {tensor.shape}')

scaler: 5
vector: tensor([1, 2, 3, 3, 5, 5])

matrix:
tensor([[ 1,  3,  4],
        [ 3, 44,  5]])

tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[11, 22, 33],
         [44, 55, 66]]])
Shape of matrix: torch.Size([2, 3])
Shape of tensor: torch.Size([2, 2, 3])


In [69]:
a = torch.randint(1,10, [3,3])
b = torch.rand(3,3)
c = torch.rand(3,3)
d = torch.rand(3,3)
e = torch.randn(4,4)
a, b, c, d, e

(tensor([[4, 1, 9],
         [3, 2, 2],
         [9, 4, 7]]),
 tensor([[0.0499, 0.0906, 0.7857],
         [0.4603, 0.5185, 0.9884],
         [0.9774, 0.8169, 0.5875]]),
 tensor([[0.4046, 0.6245, 0.9314],
         [0.0986, 0.0334, 0.0988],
         [0.9617, 0.8561, 0.6742]]),
 tensor([[0.1934, 0.6009, 0.7333],
         [0.4777, 0.3384, 0.6908],
         [0.9527, 0.6731, 0.3382]]),
 tensor([[ 0.1839,  0.4273,  0.5219,  0.0645],
         [-2.1140, -0.8268,  0.6986, -1.8377],
         [ 0.4919, -0.3256, -1.8470,  0.3910],
         [ 0.3189,  0.9564,  0.3271, -1.5561]]))

## 2. Basic Tensor Operations


### ✔ 1. Addition

```python
a + b
```

```python
torch.add(a, b)
```

=> Element-wise addition

---

In [70]:
add_ab = torch.add(a,b)
add_ab_ = a+b
print(add_ab)
print(add_ab_)

tensor([[4.0499, 1.0906, 9.7857],
        [3.4603, 2.5185, 2.9884],
        [9.9774, 4.8169, 7.5875]])
tensor([[4.0499, 1.0906, 9.7857],
        [3.4603, 2.5185, 2.9884],
        [9.9774, 4.8169, 7.5875]])


### ✔ 2. Subtraction

```python
a - b
```

```python
torch.sub(a, b)
```

---

In [71]:
sub_ab = torch.sub(a, b)
print(sub_ab)
print(a-b)

tensor([[3.9501, 0.9094, 8.2143],
        [2.5397, 1.4815, 1.0116],
        [8.0226, 3.1831, 6.4125]])
tensor([[3.9501, 0.9094, 8.2143],
        [2.5397, 1.4815, 1.0116],
        [8.0226, 3.1831, 6.4125]])


### `alpha` and `out` parameters
---

###  1. `alpha` Parameter

#### ✔ Definition

A **scaling factor** applied to one of the operands before the operation.

---

## ✔ Syntax Example

```python
torch.add(input, other, alpha=1)
```

---

#### ✔ How it works

```python
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

torch.add(a, b, alpha=2)
```

=> Internally:

```
a + (alpha * b)
→ a + (2 * b)
```

=> Result:

```python
[1 + 8, 2 + 10, 3 + 12]
```

---

## ✔ Used in:

* `torch.add()`
* `torch.sub()`

### Example in subtraction:

```python
torch.sub(a, b, alpha=2)
```

=> Means:

```
a - (2 * b)
```

---

#### ✔ Key Insight

`alpha` helps avoid writing extra multiplication → improves **computational efficiency**.

---

###  2. `out` Parameter

#### ✔ Definition

Specifies a **pre-allocated tensor** where the result will be stored.

---

#### ✔ Syntax Example

```python
torch.add(a, b, out=result_tensor)
```

---

#### ✔ Example

```python
result = torch.empty(3)

torch.add(a, b, out=result)
```

=> Instead of creating a new tensor, result is stored in `result`.

---

#### ✔ Why important?

* Avoids **extra memory allocation**
* Improves **performance in large computations**
* Useful in **high-performance pipelines**

---

###  3. Combined Usage

```python
result = torch.empty(3)

torch.add(a, b, alpha=2, out=result)
```

=> Operation:

```
result = a + (2 * b)
```

---

###  4. Important Notes

### ✔ Not all functions support `alpha`

* Supported: `add`, `sub`
* Not supported: `mul`, `div`

---

##### ✔ `out` must match:

* Shape
* dtype
* device

Otherwise → runtime error

---

##### ✔ Alternative: In-place operations

```python
a.add_(b)
```

=> Similar to `out`, but modifies original tensor

---

###  Conceptual Difference

| Parameter | Purpose                                  |
| --------- | ---------------------------------------- |
| `alpha`   | Scales operand before operation          |
| `out`     | Controls memory (where result is stored) |

---

###  Vocabulary Boost

* **Scaling factor** → multiplier applied before operation
* **Pre-allocated memory** → memory reserved before computation
* **In-place operation** → modifies original data
* **Memory optimization** → reducing unnecessary allocations

---

### 🔥 Practical Understanding

* Use `alpha` → when you want **weighted operations efficiently**
* Use `out` → when working with **large tensors / performance-critical code**

---


In [72]:
x = torch.empty(size=(3,3), dtype=torch.float32)
y = torch.empty(size=(3,3))
x,y 

(tensor([[3.9501, 0.9094, 8.2143],
         [2.5397, 1.4815, 1.0116],
         [8.0226, 3.1831, 6.4125]]),
 tensor([[5.0763, 1.6126, 8.8501],
         [2.7846, 6.4099, 1.6569],
         [2.3243, 6.3421, 5.9673]]))

In [73]:
torch.add(a,b, out=x)
torch.add(b,a, alpha=10, out=y)
print(a+b)
print(x,'\n')

print(torch.add(a,b, alpha=10))
print(a+10*b)
print('\n',y)
print(b+a*10)

tensor([[4.0499, 1.0906, 9.7857],
        [3.4603, 2.5185, 2.9884],
        [9.9774, 4.8169, 7.5875]])
tensor([[4.0499, 1.0906, 9.7857],
        [3.4603, 2.5185, 2.9884],
        [9.9774, 4.8169, 7.5875]]) 

tensor([[ 4.4990,  1.9062, 16.8574],
        [ 7.6033,  7.1848, 11.8841],
        [18.7745, 12.1687, 12.8751]])
tensor([[ 4.4990,  1.9062, 16.8574],
        [ 7.6033,  7.1848, 11.8841],
        [18.7745, 12.1687, 12.8751]])

 tensor([[40.0499, 10.0906, 90.7857],
        [30.4603, 20.5185, 20.9884],
        [90.9774, 40.8169, 70.5875]])
tensor([[40.0499, 10.0906, 90.7857],
        [30.4603, 20.5185, 20.9884],
        [90.9774, 40.8169, 70.5875]])


### ✔ 3. Multiplication (Element-wise)

```python
a * b
```

```python
torch.mul(a, b)
```

---

In [74]:
mul_ab = torch.mul(a,b)
print(mul_ab)
print(a*b)

tensor([[0.1996, 0.0906, 7.0717],
        [1.3810, 1.0370, 1.9768],
        [8.7970, 3.2675, 4.1126]])
tensor([[0.1996, 0.0906, 7.0717],
        [1.3810, 1.0370, 1.9768],
        [8.7970, 3.2675, 4.1126]])


## ✔ 4. Division

```python
a / b
```

```python
torch.div(a, b)
```

---

In [75]:
div_ab = torch.div(a,b)
print(div_ab)
print(a/b)

tensor([[80.1591, 11.0347, 11.4541],
        [ 6.5171,  3.8574,  2.0234],
        [ 9.2077,  4.8967, 11.9147]])
tensor([[80.1591, 11.0347, 11.4541],
        [ 6.5171,  3.8574,  2.0234],
        [ 9.2077,  4.8967, 11.9147]])


## 3. Matrix Multiplication (Important)

```python
torch.matmul(a, b)
```

or

```python
a @ b
```

=> Not element-wise
=> Follows **linear algebra rules**

---

In [76]:
a.dtype, b.dtype

(torch.int64, torch.float32)

In [77]:
try:
    mat_mul_ab = torch.matmul(a,b)
    print(mat_mul_ab)
    print(a @ b)
except Exception as e:
    print(f'❌ -->> {e}')

❌ -->> expected m1 and m2 to have the same dtype, but got: __int64 != float


## --> How to change dtype of a tensor (already declared)
Facing a **dtype mismatch error**, which is common in PyTorch operations like `matmul`.

---

###  Problem Restated

* `a.dtype = torch.int64`
* `b.dtype = torch.float32`
* `torch.matmul(a, b)` → ❌ Error

=> Reason: **Both tensors must have the same dtype**

---

###  How to Change dtype (Core Methods)

#### ✔ 1. Using `.to()` (Most Recommended)

```python
a = a.to(torch.float32)
```

✔ Flexible (can also change device)

---

### ✔ 2. Using Type-Specific Methods

```python
a = a.float()     # → float32
a = a.int()       # → int32
a = a.long()      # → int64
a = a.double()    # → float64
```

=> These are **shortcuts (syntactic sugar)** for `.to()`

---

#### ✔ 3. Using `.type()`

```python
a = a.type(torch.float32)
```

⚠️ Older style, less preferred

---

###  Fix Your Code

```python
a = a.float()   # convert int → float

mat_mul_ab = torch.matmul(a, b)

print(mat_mul_ab)
print(a @ b)
```

---

###  Important Insight

=> PyTorch does **not automatically cast types** in operations like NumPy sometimes does.

This is called:

* **Strict type enforcement**

---

###  Best Practice

Before operations like:

* `matmul`
* `add`
* `loss functions`

✔ Always ensure:

#### ```a.dtype == b.dtype```

---

###  Pro Tip (Efficient Handling)

Instead of converting both:

```python
a = a.to(b.dtype)
```

=> This ensures compatibility dynamically

---

###  Vocabulary Boost

* **Type casting** → converting one dtype to another
* **dtype mismatch** → incompatible data types
* **Strict typing** → no implicit conversion
* **Syntactic sugar** → shortcut method

---

### 🔥 Practical Takeaway

* Use `.float()` when working with neural networks
* Keep all tensors in **float32** unless there is a strong reason not to

---

#### Question:
=> “Why deep learning prefers float32 over int” — this will connect directly to training mechanics.


In [78]:
print(a.dtype == b.dtype)
print(f'DataType of a = {a.dtype}, b = {b.dtype}')

#changing the dype of a to int
a = a.float()
print(f'DataType of a = {a.dtype}, b = {b.dtype}')

mat_mul_ab = torch.matmul(a,b,)
print(mat_mul_ab)
print(a@b)

print(mat_mul_ab == a@b)

False
DataType of a = torch.int64, b = torch.float32
DataType of a = torch.float32, b = torch.float32
tensor([[ 9.4570,  8.2329,  9.4190],
        [ 3.0253,  2.9426,  5.5091],
        [ 9.1325,  8.6077, 15.1379]])
tensor([[ 9.4570,  8.2329,  9.4190],
        [ 3.0253,  2.9426,  5.5091],
        [ 9.1325,  8.6077, 15.1379]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## 4. Scalar Operations

```python
a + 5
a - 3
a * 2
a / 9
```

=> Scalar is applied to every element

---

In [79]:
print(a)
a += 5
print(f'a + 5 = \n{a}\n')
a -= 5
print(f'a - 5 = \n{a}\n')
a *= 5
print(f'a * 5 = \n{a}\n')
a /= 5
print(f'a / 5 = \n{a}\n')

tensor([[4., 1., 9.],
        [3., 2., 2.],
        [9., 4., 7.]])
a + 5 = 
tensor([[ 9.,  6., 14.],
        [ 8.,  7.,  7.],
        [14.,  9., 12.]])

a - 5 = 
tensor([[4., 1., 9.],
        [3., 2., 2.],
        [9., 4., 7.]])

a * 5 = 
tensor([[20.,  5., 45.],
        [15., 10., 10.],
        [45., 20., 35.]])

a / 5 = 
tensor([[4., 1., 9.],
        [3., 2., 2.],
        [9., 4., 7.]])



## 5. Broadcasting (Very Important Concept)

```python
a + b
```

Even if shapes differ, PyTorch tries to **auto-adjust shapes**

### Example:

```python
a = torch.tensor([[1,2,3],
                  [4,5,6]])

b = torch.tensor([1,2,3])

a + b
```

=> `b` is broadcasted across rows

---

In [80]:
z = torch.randint(0, 5, (1,3))
print(f'z:\n{z}')
print(f'x:\n{x}')
print(x.shape)
print(f'x and z have same shape: {z.shape == x.shape}')
print(f'a+b:\n{x+z}')
print(f'\nNOTE: Tensor z is braodcased to each row of x\n')

z1 = torch.randint(0, 5, (1,4))

try:
    print(f'a+b:\n{x+z1}')
except Exception as e:
    print(f'❌ Error: {e}')

z:
tensor([[2, 2, 2]])
x:
tensor([[4.0499, 1.0906, 9.7857],
        [3.4603, 2.5185, 2.9884],
        [9.9774, 4.8169, 7.5875]])
torch.Size([3, 3])
x and z have same shape: False
a+b:
tensor([[ 6.0499,  3.0906, 11.7857],
        [ 5.4603,  4.5185,  4.9884],
        [11.9774,  6.8169,  9.5875]])

NOTE: Tensor z is braodcased to each row of x

❌ Error: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1


## 6. Aggregation Operations
**Aggregation operation:** A computation that reduces multiple tensor elements into a single value or a smaller set of values (e.g., sum, mean).


#### Sum
```torch.sum(a)```

#### Mean
```torch.mean(a.float())```

#### Max / Min
```
torch.max(a)
torch.min(a)
```


##### All Aggregation Operations:
```python
torch.sum       -> sum = total of all elements
torch.mean      -> mean = average of all elements
torch.max       -> max = maximum element value
torch.min       -> min = minimum element value
torch.argmax    -> argmax = index of maximum element (flattened index)
torch.argmin    -> argmin = index of minimum element (flattened index)
torch.prod      -> prod = product of all elements
torch.std       -> std = standard deviation (spread of data)
torch.var       -> var = variance (measure of dispersion)
torch.median    -> median = middle value after sorting
torch.mode      -> mode = most frequent element
torch.norm      -> norm = magnitude/length of tensor
torch.all       -> all = True if all elements are True
torch.any       -> any = True if at least one element is True
```


---

##### torch.opperation(tensor_name) -> attribute
##### tensor_name.opeartion() -> Method

---

In [81]:
print(a)
a[2][2] = 1111
# Sum of all elements:
print(f'Sum of all elements: {torch.sum(a)}\t{a.sum()}')
print(f'Mean of all elements: {torch.mean(a)}\t{a.mean()}')
print(f'Maximun element: {a.max()}')
print(f'Minimum element: {a.min()}')
print(f'argmax: {torch.argmax(a)}\t{a.argmax()}')

print(a[2][2])

print(f'Median of all elements: {a.mean()}')
print(f'Satandard deviation of tensor a: {a.std()}')
print(f'Varience of tensor a: {a.var()}')
print(f'{a.all()}')

tensor([[4., 1., 9.],
        [3., 2., 2.],
        [9., 4., 7.]])
Sum of all elements: 1145.0	1145.0
Mean of all elements: 127.22222137451172	127.22222137451172
Maximun element: 1111.0
Minimum element: 1.0
argmax: 8	8
tensor(1111.)
Median of all elements: 127.22222137451172
Satandard deviation of tensor a: 368.9281005859375
Varience of tensor a: 136107.9375
True


## 7. Indexing & Slicing

```python
a[0]        # first row
a[:, 1]     # second column
a[0,1]      # specific element
```

Indexing: a[ ][ ] .. [ ]

Slicing: a[row, column]

---

In [82]:
print(x)
print(f'First row of x: {x[0]}\n\tDataType: {x[0].dtype}\n\tShape: {x[0].shape}')
print(f'Second row of x: {x[1]}')
print(f'Third row of x: {x[2]}')
print(f'From 1st row second elememt to first row last elements:\n{x[0, 1:]}')
print(f'2nd element of 3rd row: {x[1][2]}')

tensor([[4.0499, 1.0906, 9.7857],
        [3.4603, 2.5185, 2.9884],
        [9.9774, 4.8169, 7.5875]])
First row of x: tensor([4.0499, 1.0906, 9.7857])
	DataType: torch.float32
	Shape: torch.Size([3])
Second row of x: tensor([3.4603, 2.5185, 2.9884])
Third row of x: tensor([9.9774, 4.8169, 7.5875])
From 1st row second elememt to first row last elements:
tensor([1.0906, 9.7857])
2nd element of 3rd row: 2.9884119033813477


## 8. Shape Operations

#### Reshape

```python
a.reshape(2,3)
```

#### View (memory-efficient)

```python
a.view(2,3)
```

**Use of `view()`**: To **reshape a tensor efficiently without copying data**, mainly for preparing tensor shapes (e.g., flattening before feeding into a neural network) while keeping memory usage optimal.

#### Transpose

```python
a.mT
```

##### Note : a.T showing depreciaiton error so always use a.mT

---


In [83]:
print(z)
print(z.shape)
print(z.reshape(3,1))
z2 = z.reshape(1,1,1,1,1,1,1,1,1,1,1,1,1,3)
print(f'z2:\n{z2}\nShape of z2: {z2.shape}')
print(z2.view(1,3))
print(z2.mT)

tensor([[2, 2, 2]])
torch.Size([1, 3])
tensor([[2],
        [2],
        [2]])
z2:
tensor([[[[[[[[[[[[[[2, 2, 2]]]]]]]]]]]]]])
Shape of z2: torch.Size([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3])
tensor([[2, 2, 2]])
tensor([[[[[[[[[[[[[[2],
                    [2],
                    [2]]]]]]]]]]]]]])


## 9. Comparison Operations

```python
a > b
a == b
```

👉 Returns boolean tensor

---

In [84]:
print(a>b)
print(a==b)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


## 10. In-place Operations (Advanced)

```python
a.add_(b)
a.mul_(2)
```

👉 `_` means **modifies original tensor**

---

In [85]:
print(a)
a.add_(33)
print(a-33)
print(a.add_(3))
print(a)

tensor([[4.0000e+00, 1.0000e+00, 9.0000e+00],
        [3.0000e+00, 2.0000e+00, 2.0000e+00],
        [9.0000e+00, 4.0000e+00, 1.1110e+03]])
tensor([[4.0000e+00, 1.0000e+00, 9.0000e+00],
        [3.0000e+00, 2.0000e+00, 2.0000e+00],
        [9.0000e+00, 4.0000e+00, 1.1110e+03]])
tensor([[  40.,   37.,   45.],
        [  39.,   38.,   38.],
        [  45.,   40., 1147.]])
tensor([[  40.,   37.,   45.],
        [  39.,   38.,   38.],
        [  45.,   40., 1147.]])


---

#### Key Insight

All operations are:

* **Vectorized** (no loops needed)
* Optimized for **parallel computation**

This is a core computational paradigm in deep learning.

---

#### Vocabulary Boost

* **Element-wise** → operation applied to each element
* **Broadcasting** → automatic shape alignment
* **Aggregation** → reducing tensor to summary value
* **Vectorization** → avoiding explicit loops

---

## Important Errors to remembers

In [86]:
float_32_tensor = torch.rand((3,3), dtype=torch.float32)
float_64_tensor = torch.rand((3,3), dtype=torch.float64)
print(float_32_tensor * float_64_tensor)
try:
    print(float_32_tensor @ float_64_tensor) ## REMEMBER SAME DATATYPE TOO
except Exception as e:
    print(f'❌ Error occured: {e}')

tensor([[0.0171, 0.2551, 0.1702],
        [0.1522, 0.0256, 0.3496],
        [0.4352, 0.0168, 0.0653]], dtype=torch.float64)
❌ Error occured: expected m1 and m2 to have the same dtype, but got: float != double


In [87]:
int_tensor = torch.randint(1,10, (3,3))
try:
    torch.mean(int_tensor)
except Exception as e:
    print(f'❌ Error occured: {e}')
try:
    int_tensor.mean()
except Exception as e:
    print(f'❌ Error occured: {e}')
    
'''
NOTE: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
'''

❌ Error occured: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
❌ Error occured: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


'\nNOTE: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long\n'