In [1]:
import torch

## 1. Basic Matrix Representation in PyTorch

---

### Tensor Types (Quick Recap)

| Type   | Dimension | Example         |
| ------ | --------- | --------------- |
| Scalar | 0D        | `5`             |
| Vector | 1D        | `[1,2,3]`       |
| Matrix | 2D        | `[[1,2],[3,4]]` |
| Tensor | nD        | `3D, 4D...`     |

---

In [2]:
scaler = torch.tensor(5)
vector = torch.tensor([1,2,3,3,5,5])
matrix = torch.tensor([[1,3,4],
                       [3,44,5]])
tensor = torch.tensor([[[1,2,3],
                        [4,5,6]],
                       
                       [[11,22,33],
                       [44,55,66]]])
print(f'scaler: {scaler}\nvector: {vector}\n\nmatrix:\n{matrix}\n\ntensor:\n{tensor}')
print(f'Shape of matrix: {matrix.shape}\nShape of tensor: {tensor.shape}')

scaler: 5
vector: tensor([1, 2, 3, 3, 5, 5])

matrix:
tensor([[ 1,  3,  4],
        [ 3, 44,  5]])

tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[11, 22, 33],
         [44, 55, 66]]])
Shape of matrix: torch.Size([2, 3])
Shape of tensor: torch.Size([2, 2, 3])


In [3]:
a = torch.randint(1,10, [3,3])
b = torch.rand(3,3)
c = torch.rand(3,3)
d = torch.rand(3,3)
a, b, c, d

(tensor([[3, 3, 7],
         [6, 4, 8],
         [6, 4, 7]]),
 tensor([[0.9274, 0.7622, 0.0686],
         [0.8585, 0.4866, 0.7095],
         [0.0142, 0.6514, 0.0599]]),
 tensor([[0.6016, 0.1406, 0.9752],
         [0.2335, 0.2127, 0.5352],
         [0.3178, 0.7889, 0.8404]]),
 tensor([[0.7820, 0.6766, 0.8203],
         [0.5094, 0.8981, 0.9712],
         [0.4062, 0.4508, 0.8146]]))

## 2. Basic Tensor Operations


### ✔ 1. Addition

```python
a + b
```

```python
torch.add(a, b)
```

=> Element-wise addition

---

In [4]:
add_ab = torch.add(a,b)
add_ab_ = a+b
print(add_ab)
print(add_ab_)

tensor([[3.9274, 3.7622, 7.0686],
        [6.8585, 4.4866, 8.7095],
        [6.0142, 4.6514, 7.0599]])
tensor([[3.9274, 3.7622, 7.0686],
        [6.8585, 4.4866, 8.7095],
        [6.0142, 4.6514, 7.0599]])


### ✔ 2. Subtraction

```python
a - b
```

```python
torch.sub(a, b)
```

---

In [11]:
sub_ab = torch.sub(a, b)
print(sub_ab)

tensor([[2.0726, 2.2378, 6.9314],
        [5.1415, 3.5134, 7.2905],
        [5.9858, 3.3486, 6.9401]])


### `alpha` and `out` parameters
---

###  1. `alpha` Parameter

#### ✔ Definition

A **scaling factor** applied to one of the operands before the operation.

---

## ✔ Syntax Example

```python
torch.add(input, other, alpha=1)
```

---

#### ✔ How it works

```python
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

torch.add(a, b, alpha=2)
```

=> Internally:

```
a + (alpha * b)
→ a + (2 * b)
```

=> Result:

```python
[1 + 8, 2 + 10, 3 + 12]
```

---

## ✔ Used in:

* `torch.add()`
* `torch.sub()`

### Example in subtraction:

```python
torch.sub(a, b, alpha=2)
```

=> Means:

```
a - (2 * b)
```

---

#### ✔ Key Insight

`alpha` helps avoid writing extra multiplication → improves **computational efficiency**.

---

###  2. `out` Parameter

#### ✔ Definition

Specifies a **pre-allocated tensor** where the result will be stored.

---

#### ✔ Syntax Example

```python
torch.add(a, b, out=result_tensor)
```

---

#### ✔ Example

```python
result = torch.empty(3)

torch.add(a, b, out=result)
```

=> Instead of creating a new tensor, result is stored in `result`.

---

#### ✔ Why important?

* Avoids **extra memory allocation**
* Improves **performance in large computations**
* Useful in **high-performance pipelines**

---

###  3. Combined Usage

```python
result = torch.empty(3)

torch.add(a, b, alpha=2, out=result)
```

=> Operation:

```
result = a + (2 * b)
```

---

###  4. Important Notes

### ✔ Not all functions support `alpha`

* Supported: `add`, `sub`
* Not supported: `mul`, `div`

---

##### ✔ `out` must match:

* Shape
* dtype
* device

Otherwise → runtime error

---

##### ✔ Alternative: In-place operations

```python
a.add_(b)
```

=> Similar to `out`, but modifies original tensor

---

###  Conceptual Difference

| Parameter | Purpose                                  |
| --------- | ---------------------------------------- |
| `alpha`   | Scales operand before operation          |
| `out`     | Controls memory (where result is stored) |

---

###  Vocabulary Boost

* **Scaling factor** → multiplier applied before operation
* **Pre-allocated memory** → memory reserved before computation
* **In-place operation** → modifies original data
* **Memory optimization** → reducing unnecessary allocations

---

### 🔥 Practical Understanding

* Use `alpha` → when you want **weighted operations efficiently**
* Use `out` → when working with **large tensors / performance-critical code**

---
