In [2]:
import torch

## 1. Basic Matrix Representation in PyTorch

---

### Tensor Types (Quick Recap)

| Type   | Dimension | Example         |
| ------ | --------- | --------------- |
| Scalar | 0D        | `5`             |
| Vector | 1D        | `[1,2,3]`       |
| Matrix | 2D        | `[[1,2],[3,4]]` |
| Tensor | nD        | `3D, 4D...`     |

---

In [3]:
scaler = torch.tensor(5)
vector = torch.tensor([1,2,3,3,5,5])
matrix = torch.tensor([[1,3,4],
                       [3,44,5]])
tensor = torch.tensor([[[1,2,3],
                        [4,5,6]],
                       
                       [[11,22,33],
                       [44,55,66]]])
print(f'scaler: {scaler}\nvector: {vector}\n\nmatrix:\n{matrix}\n\ntensor:\n{tensor}')
print(f'Shape of matrix: {matrix.shape}\nShape of tensor: {tensor.shape}')

scaler: 5
vector: tensor([1, 2, 3, 3, 5, 5])

matrix:
tensor([[ 1,  3,  4],
        [ 3, 44,  5]])

tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[11, 22, 33],
         [44, 55, 66]]])
Shape of matrix: torch.Size([2, 3])
Shape of tensor: torch.Size([2, 2, 3])


In [4]:
a = torch.randint(1,10, [3,3])
b = torch.rand(3,3)
c = torch.rand(3,3)
d = torch.rand(3,3)
a, b, c, d

(tensor([[2, 8, 8],
         [9, 9, 9],
         [4, 3, 9]]),
 tensor([[0.5312, 0.6291, 0.7061],
         [0.4364, 0.0546, 0.8255],
         [0.0880, 0.4162, 0.0384]]),
 tensor([[0.5838, 0.5659, 0.2334],
         [0.2317, 0.9056, 0.4951],
         [0.6525, 0.7962, 0.5316]]),
 tensor([[0.0381, 0.3941, 0.7488],
         [0.3961, 0.9507, 0.0118],
         [0.9964, 0.9040, 0.3134]]))

## 2. Basic Tensor Operations


### ✔ 1. Addition

```python
a + b
```

```python
torch.add(a, b)
```

=> Element-wise addition

---

In [5]:
add_ab = torch.add(a,b)
add_ab_ = a+b
print(add_ab)
print(add_ab_)

tensor([[2.5312, 8.6291, 8.7061],
        [9.4364, 9.0546, 9.8255],
        [4.0880, 3.4162, 9.0384]])
tensor([[2.5312, 8.6291, 8.7061],
        [9.4364, 9.0546, 9.8255],
        [4.0880, 3.4162, 9.0384]])


### ✔ 2. Subtraction

```python
a - b
```

```python
torch.sub(a, b)
```

---

In [6]:
sub_ab = torch.sub(a, b)
print(sub_ab)

tensor([[1.4688, 7.3709, 7.2939],
        [8.5636, 8.9454, 8.1745],
        [3.9120, 2.5838, 8.9616]])


### `alpha` and `out` parameters
---

###  1. `alpha` Parameter

#### ✔ Definition

A **scaling factor** applied to one of the operands before the operation.

---

## ✔ Syntax Example

```python
torch.add(input, other, alpha=1)
```

---

#### ✔ How it works

```python
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

torch.add(a, b, alpha=2)
```

=> Internally:

```
a + (alpha * b)
→ a + (2 * b)
```

=> Result:

```python
[1 + 8, 2 + 10, 3 + 12]
```

---

## ✔ Used in:

* `torch.add()`
* `torch.sub()`

### Example in subtraction:

```python
torch.sub(a, b, alpha=2)
```

=> Means:

```
a - (2 * b)
```

---

#### ✔ Key Insight

`alpha` helps avoid writing extra multiplication → improves **computational efficiency**.

---

###  2. `out` Parameter

#### ✔ Definition

Specifies a **pre-allocated tensor** where the result will be stored.

---

#### ✔ Syntax Example

```python
torch.add(a, b, out=result_tensor)
```

---

#### ✔ Example

```python
result = torch.empty(3)

torch.add(a, b, out=result)
```

=> Instead of creating a new tensor, result is stored in `result`.

---

#### ✔ Why important?

* Avoids **extra memory allocation**
* Improves **performance in large computations**
* Useful in **high-performance pipelines**

---

###  3. Combined Usage

```python
result = torch.empty(3)

torch.add(a, b, alpha=2, out=result)
```

=> Operation:

```
result = a + (2 * b)
```

---

###  4. Important Notes

### ✔ Not all functions support `alpha`

* Supported: `add`, `sub`
* Not supported: `mul`, `div`

---

##### ✔ `out` must match:

* Shape
* dtype
* device

Otherwise → runtime error

---

##### ✔ Alternative: In-place operations

```python
a.add_(b)
```

=> Similar to `out`, but modifies original tensor

---

###  Conceptual Difference

| Parameter | Purpose                                  |
| --------- | ---------------------------------------- |
| `alpha`   | Scales operand before operation          |
| `out`     | Controls memory (where result is stored) |

---

###  Vocabulary Boost

* **Scaling factor** → multiplier applied before operation
* **Pre-allocated memory** → memory reserved before computation
* **In-place operation** → modifies original data
* **Memory optimization** → reducing unnecessary allocations

---

### 🔥 Practical Understanding

* Use `alpha` → when you want **weighted operations efficiently**
* Use `out` → when working with **large tensors / performance-critical code**

---


In [7]:
x = torch.empty(size=(3,3), dtype=torch.float32)
y = torch.empty(size=(3,3))
x,y 

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [8]:
torch.add(a,b, out=x)
torch.add(b,a, alpha=10, out=y)
print(a+b)
print(x,'\n')

print(torch.add(a,b, alpha=10))
print(a+10*b)
print('\n',y)
print(b+a*10)

tensor([[2.5312, 8.6291, 8.7061],
        [9.4364, 9.0546, 9.8255],
        [4.0880, 3.4162, 9.0384]])
tensor([[2.5312, 8.6291, 8.7061],
        [9.4364, 9.0546, 9.8255],
        [4.0880, 3.4162, 9.0384]]) 

tensor([[ 7.3116, 14.2907, 15.0608],
        [13.3643,  9.5459, 17.2554],
        [ 4.8805,  7.1624,  9.3840]])
tensor([[ 7.3116, 14.2907, 15.0608],
        [13.3643,  9.5459, 17.2554],
        [ 4.8805,  7.1624,  9.3840]])

 tensor([[20.5312, 80.6291, 80.7061],
        [90.4364, 90.0546, 90.8255],
        [40.0881, 30.4162, 90.0384]])
tensor([[20.5312, 80.6291, 80.7061],
        [90.4364, 90.0546, 90.8255],
        [40.0881, 30.4162, 90.0384]])


### ✔ 3. Multiplication (Element-wise)

```python
a * b
```

```python
torch.mul(a, b)
```

---

In [9]:
mul_ab = torch.mul(a,b)
print(mul_ab)
print(a*b)

tensor([[1.0623, 5.0326, 5.6487],
        [3.9278, 0.4913, 7.4298],
        [0.3522, 1.2487, 0.3456]])
tensor([[1.0623, 5.0326, 5.6487],
        [3.9278, 0.4913, 7.4298],
        [0.3522, 1.2487, 0.3456]])


## ✔ 4. Division

```python
a / b
```

```python
torch.div(a, b)
```

---

In [10]:
div_ab = torch.div(a,b)
print(div_ab)
print(a/b)

tensor([[  3.7653,  12.7172,  11.3301],
        [ 20.6220, 164.8611,  10.9020],
        [ 45.4291,   7.2074, 234.3623]])
tensor([[  3.7653,  12.7172,  11.3301],
        [ 20.6220, 164.8611,  10.9020],
        [ 45.4291,   7.2074, 234.3623]])


## 3. Matrix Multiplication (Important)

```python
torch.matmul(a, b)
```

or

```python
a @ b
```

=> Not element-wise
=> Follows **linear algebra rules**

---

In [11]:
a.dtype, b.dtype

(torch.int64, torch.float32)

In [12]:
try:
    mat_mul_ab = torch.matmul(a,b)
    print(mat_mul_ab)
    print(a @ b)
except Exception as e:
    print(f'❌ -->> {e}')

❌ -->> expected m1 and m2 to have the same dtype, but got: __int64 != float


## --> How to change dtype of a tensor (already declared)
Facing a **dtype mismatch error**, which is common in PyTorch operations like `matmul`.

---

###  Problem Restated

* `a.dtype = torch.int64`
* `b.dtype = torch.float32`
* `torch.matmul(a, b)` → ❌ Error

=> Reason: **Both tensors must have the same dtype**

---

###  How to Change dtype (Core Methods)

#### ✔ 1. Using `.to()` (Most Recommended)

```python
a = a.to(torch.float32)
```

✔ Flexible (can also change device)

---

### ✔ 2. Using Type-Specific Methods

```python
a = a.float()     # → float32
a = a.int()       # → int32
a = a.long()      # → int64
a = a.double()    # → float64
```

=> These are **shortcuts (syntactic sugar)** for `.to()`

---

#### ✔ 3. Using `.type()`

```python
a = a.type(torch.float32)
```

⚠️ Older style, less preferred

---

###  Fix Your Code

```python
a = a.float()   # convert int → float

mat_mul_ab = torch.matmul(a, b)

print(mat_mul_ab)
print(a @ b)
```

---

###  Important Insight

=> PyTorch does **not automatically cast types** in operations like NumPy sometimes does.

This is called:

* **Strict type enforcement**

---

###  Best Practice

Before operations like:

* `matmul`
* `add`
* `loss functions`

✔ Always ensure:

#### ```a.dtype == b.dtype```

---

###  Pro Tip (Efficient Handling)

Instead of converting both:

```python
a = a.to(b.dtype)
```

=> This ensures compatibility dynamically

---

###  Vocabulary Boost

* **Type casting** → converting one dtype to another
* **dtype mismatch** → incompatible data types
* **Strict typing** → no implicit conversion
* **Syntactic sugar** → shortcut method

---

### 🔥 Practical Takeaway

* Use `.float()` when working with neural networks
* Keep all tensors in **float32** unless there is a strong reason not to

---

#### Question:
=> “Why deep learning prefers float32 over int” — this will connect directly to training mechanics.


In [13]:
print(a.dtype == b.dtype)
print(f'DataType of a = {a.dtype}, b = {b.dtype}')

#changing the dype of a to int
a = a.float()
print(f'DataType of a = {a.dtype}, b = {b.dtype}')

mat_mul_ab = torch.matmul(a,b,)
print(mat_mul_ab)
print(a@b)

print(mat_mul_ab == a@b)

False
DataType of a = torch.int64, b = torch.float32
DataType of a = torch.float32, b = torch.float32
tensor([[ 5.2581,  5.0248,  8.3237],
        [ 9.5008,  9.8991, 14.1302],
        [ 4.2264,  6.4262,  5.6466]])
tensor([[ 5.2581,  5.0248,  8.3237],
        [ 9.5008,  9.8991, 14.1302],
        [ 4.2264,  6.4262,  5.6466]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## 4. Scalar Operations

```python
a + 5
a - 3
a * 2
a / 9
```

=> Scalar is applied to every element

---

In [14]:
print(a)
a += 5
print(f'a + 5 = \n{a}\n')
a -= 5
print(f'a - 5 = \n{a}\n')
a *= 5
print(f'a * 5 = \n{a}\n')
a /= 5
print(f'a / 5 = \n{a}\n')

tensor([[2., 8., 8.],
        [9., 9., 9.],
        [4., 3., 9.]])
a + 5 = 
tensor([[ 7., 13., 13.],
        [14., 14., 14.],
        [ 9.,  8., 14.]])

a - 5 = 
tensor([[2., 8., 8.],
        [9., 9., 9.],
        [4., 3., 9.]])

a * 5 = 
tensor([[10., 40., 40.],
        [45., 45., 45.],
        [20., 15., 45.]])

a / 5 = 
tensor([[2., 8., 8.],
        [9., 9., 9.],
        [4., 3., 9.]])



## 5. Broadcasting (Very Important Concept)

```python
a + b
```

Even if shapes differ, PyTorch tries to **auto-adjust shapes**

### Example:

```python
a = torch.tensor([[1,2,3],
                  [4,5,6]])

b = torch.tensor([1,2,3])

a + b
```

=> `b` is broadcasted across rows

---

In [15]:
z = torch.randint(0, 5, (1,3))
print(f'z:\n{z}')
print(f'x:\n{x}')
print(x.shape)
print(f'x and z have same shape: {z.shape == x.shape}')
print(f'a+b:\n{x+z}')
print(f'\nNOTE: Tensor z is braodcased to each row of x\n')

z1 = torch.randint(0, 5, (1,4))

try:
    print(f'a+b:\n{x+z1}')
except Exception as e:
    print(f'❌ Error: {e}')

z:
tensor([[3, 2, 1]])
x:
tensor([[2.5312, 8.6291, 8.7061],
        [9.4364, 9.0546, 9.8255],
        [4.0880, 3.4162, 9.0384]])
torch.Size([3, 3])
x and z have same shape: False
a+b:
tensor([[ 5.5312, 10.6291,  9.7061],
        [12.4364, 11.0546, 10.8255],
        [ 7.0880,  5.4162, 10.0384]])

NOTE: Tensor z is braodcased to each row of x

❌ Error: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1


## 6. Aggregation Operations
**Aggregation operation:** A computation that reduces multiple tensor elements into a single value or a smaller set of values (e.g., sum, mean).


#### Sum
```torch.sum(a)```

#### Mean
```torch.mean(a.float())```

#### Max / Min
```
torch.max(a)
torch.min(a)
```


##### All Aggregation Operations:
```python
torch.sum       -> sum = total of all elements
torch.mean      -> mean = average of all elements
torch.max       -> max = maximum element value
torch.min       -> min = minimum element value
torch.argmax    -> argmax = index of maximum element
torch.argmin    -> argmin = index of minimum element
torch.prod      -> prod = product of all elements
torch.std       -> std = standard deviation (spread of data)
torch.var       -> var = variance (measure of dispersion)
torch.median    -> median = middle value after sorting
torch.mode      -> mode = most frequent element
torch.norm      -> norm = magnitude/length of tensor
torch.all       -> all = True if all elements are True
torch.any       -> any = True if at least one element is True
```


---

##### torch.opperation(tensor_name) -> attribute
##### tensor_name.opeartion() -> Method

---

In [16]:
print(a)
a[2][2] = 1111
# Sum of all elements:
print(f'Sum of all elements: {torch.sum(a)}\t{a.sum()}')
print(f'Mean of all elements: {torch.mean(a)}\t{a.mean()}')
print(f'Maximun element: {a.max()}')
print(f'Minimum element: {a.min()}')
print(f'argmax: {torch.argmax(a)}\t{a.argmax()}')

print(a[2][2])

print(f'Median of all elements: {a.mean()}')
print(f'Satandard deviation of tensor a: {a.std()}')
print(f'Varience of tensor a: {a.var()}')
print(f'{a.all()}')

tensor([[2., 8., 8.],
        [9., 9., 9.],
        [4., 3., 9.]])
Sum of all elements: 1163.0	1163.0
Mean of all elements: 129.22222900390625	129.22222900390625
Maximun element: 1111.0
Minimum element: 2.0
argmax: 8	8
tensor(1111.)
Median of all elements: 129.22222900390625
Satandard deviation of tensor a: 368.17718505859375
Varience of tensor a: 135554.4375
True


## 7. Indexing & Slicing

```python
a[0]        # first row
a[:, 1]     # second column
a[0,1]      # specific element
```

Indexing: a[ ][ ] .. [ ]

Slicing: a[row, column]

---

In [17]:
print(x)
print(f'First row of x: {x[0]}\n\tDataType: {x[0].dtype}\n\tShape: {x[0].shape}')
print(f'Second row of x: {x[1]}')
print(f'Third row of x: {x[2]}')
print(f'From 1st row second elememt to first row last elements:\n{x[0, 1:]}')
print(f'2nd element of 3rd row: {x[1][2]}')

tensor([[2.5312, 8.6291, 8.7061],
        [9.4364, 9.0546, 9.8255],
        [4.0880, 3.4162, 9.0384]])
First row of x: tensor([2.5312, 8.6291, 8.7061])
	DataType: torch.float32
	Shape: torch.Size([3])
Second row of x: tensor([9.4364, 9.0546, 9.8255])
Third row of x: tensor([4.0880, 3.4162, 9.0384])
From 1st row second elememt to first row last elements:
tensor([8.6291, 8.7061])
2nd element of 3rd row: 9.825536727905273


## 8. Shape Operations

#### Reshape

```python
a.reshape(2,3)
```

#### View (memory-efficient)

```python
a.view(2,3)
```

**Use of `view()`**: To **reshape a tensor efficiently without copying data**, mainly for preparing tensor shapes (e.g., flattening before feeding into a neural network) while keeping memory usage optimal.

#### Transpose

```python
a.T
```

---


In [22]:
print(z)
print(z.shape)
print(z.reshape(3,1))
z2 = z.reshape(1,1,1,1,1,1,1,1,1,1,1,1,1,3)
print(f'z2:\n{z2}\nShape of z2: {z2.shape}')
print(z2.view(1,3))
print(z2.T)

tensor([[3, 2, 1]])
torch.Size([1, 3])
tensor([[3],
        [2],
        [1]])
z2:
tensor([[[[[[[[[[[[[[3, 2, 1]]]]]]]]]]]]]])
Shape of z2: torch.Size([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3])
tensor([[3, 2, 1]])
tensor([[[[[[[[[[[[[[3]]]]]]]]]]]]],












        [[[[[[[[[[[[[2]]]]]]]]]]]]],












        [[[[[[[[[[[[[1]]]]]]]]]]]]]])


C:\Users\itspr\AppData\Local\Temp\ipykernel_15256\3959137182.py:7: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3679.)
  print(z2.T)


## 9. Comparison Operations

```python
a > b
a == b
```

👉 Returns boolean tensor

---

In [ ]:
print(a>b)
print(a==b)

tensor(9)
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


## 10. In-place Operations (Advanced)

```python
a.add_(b)
a.mul_(2)
```

👉 `_` means **modifies original tensor**

---

---

#### Key Insight

All operations are:

* **Vectorized** (no loops needed)
* Optimized for **parallel computation**

This is a core computational paradigm in deep learning.

---

#### Vocabulary Boost

* **Element-wise** → operation applied to each element
* **Broadcasting** → automatic shape alignment
* **Aggregation** → reducing tensor to summary value
* **Vectorization** → avoiding explicit loops

---