## PyTorch GPU Acceleration on Integrated GPUs

PyTorch’s GPU acceleration is built primarily for **CUDA**, which works with **NVIDIA GPUs**.  
For integrated GPUs (iGPUs), support depends on the type:

---

### 1. Intel Integrated GPU

PyTorch does not natively support Intel iGPUs via CUDA, but you can use:

- **PyTorch with DirectML** (Windows only)  
- **PyTorch with OpenVINO** (Intel CPUs + iGPUs, cross-platform)

#### Example: PyTorch with DirectML (Windows)

```bash
pip install torch-directml
```

```python
import torch_directml

# Create a DirectML device
dml = torch_directml.device()

# Example tensor on iGPU
x = torch.ones((3, 3), device=dml)
print(x)
```

#### Example: PyTorch with OpenVINO

```bash
pip install openvino-dev[onnx,pytorch]
```

Then convert your PyTorch model to **OpenVINO IR** and run on Intel GPU.

---

### 2. AMD Integrated GPU

PyTorch can use AMD GPUs (including some iGPUs) via **ROCm** (Linux only, supported hardware required).

#### Example: PyTorch with ROCm

```bash
# Install ROCm-enabled PyTorch
pip install torch --index-url https://download.pytorch.org/whl/rocm5.6
```

```python
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")  # AMD ROCm reports as 'cuda'
    print("Using AMD GPU:", torch.cuda.get_device_name(0))
else:
    device = torch.device("cpu")

x = torch.ones((3, 3), device=device)
print(x)
```

---

### 3. Apple Silicon (M1/M2) Integrated GPU

PyTorch supports Apple’s **Metal Performance Shaders (MPS)** backend.

#### Example: PyTorch with MPS

```bash
pip install torch torchvision torchaudio
```

```python
import torch

if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("Using Apple MPS GPU")
else:
    device = torch.device("cpu")

x = torch.ones((3, 3), device=device)
print(x)
```

---

### 🔹 Key Points

- **NVIDIA iGPU** → Use normal CUDA (`torch.device("cuda")`)  
- **Intel iGPU** → Use **torch-directml** (Windows) or **OpenVINO**  
- **AMD iGPU** → Use **ROCm** (Linux, supported hardware)  
- **Apple iGPU** → Use **MPS backend**

---

👉 If you share your exact **iGPU model** and **OS**, AI can prepare a ready-to-run PyTorch setup tailored for it.


In [2]:
import torch

### Running tensors and Pytorch Objects on the GPUs (and making fater computations)
Gpus = Faster comutation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

## Check for GPU access with PyTorch

In [3]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print('Using AMD Integrated GPU', torch.cuda.get_device_name(0))
else:
    device = torch.device('cpu')
    print('Using cpu as device because hardware is not compatible to use igpu')

Using cpu as device because hardware is not compatible to use igpu


In [4]:
x = torch.ones((3,4), device=device)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


For PyTorch since it's capable of running compute on both GPU or CPU, it's best practice to set up device agnostic code

e.g. run on GPU if avaiable else CPU

## Some other Tensors:

#### 1. torch.linspace()
* **Definition: Creates a tensor with evenly spaced values between a start and end value.**

* Syntax: torch.linspace(start, end, steps)

* Example:  torch.linspace(0, 1, steps=5)

* → tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [6]:
linspace_tensor = torch.linspace(0, 501, 27)
print(linspace_tensor)

tensor([  0.0000,  19.2692,  38.5385,  57.8077,  77.0769,  96.3461, 115.6154,
        134.8846, 154.1538, 173.4231, 192.6923, 211.9615, 231.2308, 250.5000,
        269.7692, 289.0385, 308.3077, 327.5769, 346.8462, 366.1154, 385.3846,
        404.6539, 423.9231, 443.1923, 462.4615, 481.7308, 501.0000])


#### 2. torch.logspace()
* **Creates a tensor with values evenly spaced on a logarithmic scale (powers of a base).**

* Syntax: torch.logspace(start, end, steps, base=10)

* Example:  torch.logspace(0, 2, steps=3)

* → tensor([  1.,  10., 100.])   # 10^0, 10^1, 10^2

* *Base → number being raised to powers (default = 10)*

In [22]:
logspace_tensor = torch.logspace(start=0, end=3, steps=10, base=3)
print(logspace_tensor)
print(len(logspace_tensor))

tensor([ 1.0000,  1.4422,  2.0801,  3.0000,  4.3267,  6.2403,  9.0000, 12.9802,
        18.7208, 27.0000])
10
