In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [4]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [9]:
X_train.shape, X_test.shape

((455, 30), (114, 30))

In [ ]:
scaler = StandardScaler().fit(X_train.select_dtypes(include='number'))
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 0.53008694,  0.05609295,  0.47820047, ...,  0.54252214,
        -0.43591698, -1.09153792],
       [-0.15100718, -0.98601141, -0.17233841, ..., -0.17540649,
         0.75260114,  0.64090421],
       [ 2.12401674, -0.49969604,  1.99050816, ...,  1.00470796,
        -0.66168704, -1.03451814],
       ...,
       [-0.16513776,  1.22324984, -0.19329702, ...,  0.24826384,
         0.88645053, -0.28526756],
       [ 1.82162226, -0.47653817,  1.73982672, ...,  1.45456882,
        -0.37302389, -0.73556396],
       [ 1.08400581, -0.59232754,  1.02887773, ...,  0.56563143,
        -0.12628946, -0.11207663]])

In [14]:
encoder = LabelEncoder().fit(y_train)
y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)

In [15]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,

## Changing the numpy arrays to pytorch

In [23]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [24]:
X_train_tensor.dtype, type(X_train_tensor), X_train_tensor.shape

(torch.float64, torch.Tensor, torch.Size([455, 30]))

In [25]:
X_train_tensor

tensor([[ 0.5301,  0.0561,  0.4782,  ...,  0.5425, -0.4359, -1.0915],
        [-0.1510, -0.9860, -0.1723,  ..., -0.1754,  0.7526,  0.6409],
        [ 2.1240, -0.4997,  1.9905,  ...,  1.0047, -0.6617, -1.0345],
        ...,
        [-0.1651,  1.2232, -0.1933,  ...,  0.2483,  0.8865, -0.2853],
        [ 1.8216, -0.4765,  1.7398,  ...,  1.4546, -0.3730, -0.7356],
        [ 1.0840, -0.5923,  1.0289,  ...,  0.5656, -0.1263, -0.1121]],
       dtype=torch.float64)

In [26]:
y_train_tensor.shape

torch.Size([455])

## Defining the Model for the Nerual Network(start)

In [40]:
class MySimpleNN():
    
    def __init__(self, train_data):
        self.weights = torch.rand(train_data.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
    
    def forward(self, train_data):
        z = torch.matmul(train_data, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y_true):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1-y_pred)).mean()
        return loss
    
        

#### Important Parameters to use

In [60]:
learning_rate = 0.2
epochs = 100

### Training Pipeline

In [61]:
# create the model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
        
    # forward pass
    y_pred = model.forward(X_train_tensor)
    
    # loss calculation
    loss = model.loss_function(y_pred, y_train_tensor)
    
    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
        
    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    # print loss for each epoch
    print(f'Epoch: {epoch+1} | Loss = {loss.item()}')

    

Epoch: 1 | Loss = 3.9436929945445267
Epoch: 2 | Loss = 3.707955212880393
Epoch: 3 | Loss = 3.440717779745967
Epoch: 4 | Loss = 3.1554049954983063
Epoch: 5 | Loss = 2.8515783788525053
Epoch: 6 | Loss = 2.5389049422517704
Epoch: 7 | Loss = 2.2239569583770438
Epoch: 8 | Loss = 1.8895139349409387
Epoch: 9 | Loss = 1.5853374755960254
Epoch: 10 | Loss = 1.3325478668594892
Epoch: 11 | Loss = 1.1425536921845105
Epoch: 12 | Loss = 1.010085218149911
Epoch: 13 | Loss = 0.9199196824829633
Epoch: 14 | Loss = 0.858297695587967
Epoch: 15 | Loss = 0.8149930068275087
Epoch: 16 | Loss = 0.7836202915956604
Epoch: 17 | Loss = 0.7604926539231169
Epoch: 18 | Loss = 0.7433017932935866
Epoch: 19 | Loss = 0.7304215423569044
Epoch: 20 | Loss = 0.7206517028975785
Epoch: 21 | Loss = 0.7131179175907838
Epoch: 22 | Loss = 0.7072008859381418
Epoch: 23 | Loss = 0.7024704369072234
Epoch: 24 | Loss = 0.6986289982873609
Epoch: 25 | Loss = 0.6954685938622674
Epoch: 26 | Loss = 0.6928408394175306
Epoch: 27 | Loss = 0.6906

In [62]:
model.weights[:10], model.bias

(tensor([[ 0.0769],
         [ 0.0218],
         [ 0.0967],
         [-0.2719],
         [ 0.2236],
         [-0.0164],
         [ 0.2486],
         [-0.1434],
         [-0.0968],
         [-0.0448]], dtype=torch.float64, grad_fn=<SliceBackward0>),
 tensor([-0.4220], dtype=torch.float64, requires_grad=True))

### Evaluation

In [69]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.7).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.719298243522644
