In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

#### Load the dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [4]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


### Train Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
X_train.shape, X_test.shape

((455, 30), (114, 30))

### Scaling Numeric Columns

In [7]:
scaler = StandardScaler().fit(X_train.select_dtypes(include='number'))
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 1.76516219,  0.33230299,  1.71996026, ...,  0.70089493,
         0.50333065, -1.09488579],
       [ 0.4473609 ,  0.23482486,  0.42351583, ...,  0.4994311 ,
         1.72637919,  1.19825899],
       [-0.17803633, -0.0808186 , -0.16210548, ...,  0.4603411 ,
        -0.37321385, -0.39411282],
       ...,
       [-0.75038647, -0.25024487, -0.74813068, ..., -0.89593149,
        -1.09786615, -0.41998752],
       [ 1.78749781,  0.37640023,  1.84516206, ...,  1.50524682,
         0.27707458, -0.45718239],
       [ 0.2267967 , -0.03207954,  0.19855647, ...,  0.51446571,
         0.0951204 ,  0.0295853 ]])

### Encoding the Categorical Columns

In [9]:
encoder = LabelEncoder().fit(y_train)
y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,

## Changing the numpy arrays to pytorch

In [11]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [12]:
X_train_tensor.dtype, type(X_train_tensor), X_train_tensor.shape

(torch.float64, torch.Tensor, torch.Size([455, 30]))

In [13]:
X_train_tensor

tensor([[ 1.7652,  0.3323,  1.7200,  ...,  0.7009,  0.5033, -1.0949],
        [ 0.4474,  0.2348,  0.4235,  ...,  0.4994,  1.7264,  1.1983],
        [-0.1780, -0.0808, -0.1621,  ...,  0.4603, -0.3732, -0.3941],
        ...,
        [-0.7504, -0.2502, -0.7481,  ..., -0.8959, -1.0979, -0.4200],
        [ 1.7875,  0.3764,  1.8452,  ...,  1.5052,  0.2771, -0.4572],
        [ 0.2268, -0.0321,  0.1986,  ...,  0.5145,  0.0951,  0.0296]],
       dtype=torch.float64)

In [14]:
y_train_tensor.shape

torch.Size([455])

## Defining the Model for the Nerual Network(start)

In [15]:
class MySimpleNN():
    
    def __init__(self, train_data):
        self.weights = torch.rand(train_data.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
    
    def forward(self, train_data):
        z = torch.matmul(train_data, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y_true):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1-y_pred)).mean()
        return loss
    
        

#### Important Parameters to use

In [39]:
learning_rate = 0.08
epochs = 160

### Training Pipeline

In [40]:
# create the model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
        
    # forward pass
    y_pred = model.forward(X_train_tensor)
    
    # loss calculation
    loss = model.loss_function(y_pred, y_train_tensor)
    
    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss for each epoch
    print(f'Epoch: {epoch+1} | Loss = {loss.item()}')

    

Epoch: 1 | Loss = 3.4036011778550903
Epoch: 2 | Loss = 3.2986115107591556
Epoch: 3 | Loss = 3.1897129961935864
Epoch: 4 | Loss = 3.076246040113669
Epoch: 5 | Loss = 2.9590681924665465
Epoch: 6 | Loss = 2.8385577133578446
Epoch: 7 | Loss = 2.7099682809465455
Epoch: 8 | Loss = 2.5808324894515033
Epoch: 9 | Loss = 2.4516785042168387
Epoch: 10 | Loss = 2.3148141595175233
Epoch: 11 | Loss = 2.178606812265684
Epoch: 12 | Loss = 2.04549296674623
Epoch: 13 | Loss = 1.9137850051673464
Epoch: 14 | Loss = 1.781837721566072
Epoch: 15 | Loss = 1.6553230523313003
Epoch: 16 | Loss = 1.5352310437563546
Epoch: 17 | Loss = 1.4194698193591246
Epoch: 18 | Loss = 1.305896622002003
Epoch: 19 | Loss = 1.202935786826826
Epoch: 20 | Loss = 1.111673808298682
Epoch: 21 | Loss = 1.0328776232771988
Epoch: 22 | Loss = 0.9668329792370441
Epoch: 23 | Loss = 0.9132210530258497
Epoch: 24 | Loss = 0.8710808982072261
Epoch: 25 | Loss = 0.8388980652567568
Epoch: 26 | Loss = 0.8148251607970481
Epoch: 27 | Loss = 0.79697100

In [41]:
model.weights[:10], model.bias

(tensor([[-0.1717],
         [-0.0817],
         [-0.3974],
         [ 0.3846],
         [ 0.2421],
         [-0.2389],
         [-0.2206],
         [ 0.3066],
         [-0.1474],
         [ 0.1542]], dtype=torch.float64, grad_fn=<SliceBackward0>),
 tensor([-0.4812], dtype=torch.float64, requires_grad=True))

In [44]:
y_pred[:10]

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

### Evaluation

In [42]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.7).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6378886103630066
