In [9]:
import torch
import torch.nn as nn

```
                O       
                O           O 
features   =    O    -->    O    -->   Output
                O           O
                O       Hidden Layer
            first layer
            of features
            processing
```


In [ ]:
class One_Hidde_Layer_Model(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        
        self. linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, featuers):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        
        return out
    

In [66]:
features = torch.rand((100, 5))
features[:10, :]

tensor([[0.1596, 0.1526, 0.5550, 0.1821, 0.0694],
        [0.1819, 0.4996, 0.3726, 0.0110, 0.7569],
        [0.2200, 0.3817, 0.9264, 0.3489, 0.3434],
        [0.5387, 0.0737, 0.3776, 0.0321, 0.8254],
        [0.7654, 0.7457, 0.5308, 0.4796, 0.8596],
        [0.0262, 0.4017, 0.7086, 0.3417, 0.8210],
        [0.9309, 0.9305, 0.4857, 0.8269, 0.1175],
        [0.2905, 0.0045, 0.9984, 0.7186, 0.6476],
        [0.1652, 0.1550, 0.0099, 0.7773, 0.2003],
        [0.2117, 0.0572, 0.6259, 0.6819, 0.0758]])

In [ ]:
model = One_Hidde_Layer_Model(features.shape[1])
model(features)

print(f'Weights of Linear1:\n{model.linear1.weight}\n\tShape: {model.linear1.weight.shape}')
print('Linear1 Bias: ', model.linear1.bias)

print(f'\nWeights of Linear2:\n{model.linear2.weight}\n\tShape: {model.linear2.weight.shape}')
print('Linear2 Bias: ', model.linear2.bias)

Weights of Linear1:
Parameter containing:
tensor([[-0.3279,  0.3868,  0.1843, -0.3712,  0.1328],
        [ 0.2304,  0.0374,  0.3279,  0.0547,  0.2974],
        [-0.2899, -0.1983, -0.2381, -0.2491,  0.2359]], requires_grad=True)
	Shape: torch.Size([3, 5])
Linear1 Bias:  Parameter containing:
tensor([-0.1851,  0.1412, -0.4033], requires_grad=True)

Weights of Linear1:
Parameter containing:
tensor([[ 0.3675, -0.0410, -0.0824]], requires_grad=True)
	Shape: torch.Size([1, 3])
Linear2 Bias:  Parameter containing:
tensor([-0.0446], requires_grad=True)


In [82]:
from torchinfo import summary

summary(model, features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
One_Hidde_Layer_Model                    [100, 1]                  --
├─Linear: 1-1                            [100, 3]                  18
├─ReLU: 1-2                              [100, 3]                  --
├─Linear: 1-3                            [100, 1]                  4
├─Sigmoid: 1-4                           [100, 1]                  --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01

## Making the above Neural Network using the Squential Container

In [92]:
class Model_Seq(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.Relu(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        
    def forward(self, featuers):
        out = self.network(features)
        return out

In [93]:
model = One_Hidde_Layer_Model(features.shape[1])
model(features)

print(f'Weights of Linear1:\n{model.linear1.weight}\n\tShape: {model.linear1.weight.shape}')
print('Linear1 Bias: ', model.linear1.bias)

print(f'\nWeights of Linear2:\n{model.linear2.weight}\n\tShape: {model.linear2.weight.shape}')
print('Linear2 Bias: ', model.linear2.bias)

Weights of Linear1:
Parameter containing:
tensor([[-0.0188,  0.3595, -0.2338, -0.2354, -0.2620],
        [ 0.1004, -0.1718,  0.2575, -0.2939, -0.2847],
        [ 0.2690,  0.4248,  0.2660,  0.3290, -0.2530]], requires_grad=True)
	Shape: torch.Size([3, 5])
Linear1 Bias:  Parameter containing:
tensor([-0.0475, -0.0357,  0.2533], requires_grad=True)

Weights of Linear2:
Parameter containing:
tensor([[-0.2733, -0.2473,  0.0571]], requires_grad=True)
	Shape: torch.Size([1, 3])
Linear2 Bias:  Parameter containing:
tensor([0.5671], requires_grad=True)
